/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-04-21 12:22:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>MediSlot</title>\r\n");
      out.write("<link href=\"assets/image/icon.png\" rel=\"icon\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" />\r\n");
      out.write("<style>\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #2b92ff;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #ffffff !important;\r\n");
      out.write("	justify-content: left;\r\n");
      out.write("	align-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	color: #ffffff !important;\r\n");
      out.write("	border: 1px solid rgb(242, 242, 242); /* Add border */\r\n");
      out.write("	border-radius: 0.6rem;\r\n");
      out.write("	padding: 0.2rem; /* Add padding */\r\n");
      out.write("	margin: 1rem;\r\n");
      out.write("	transition: transform 0.3s ease; /* Smooth transition on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("	border-color: rgba(56, 75, 179, 0.5); /* Change border color on hover */\r\n");
      out.write("	transform: translateY(-3px); /* Move link up slightly */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jumbotron {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-around; /* Center content horizontally */\r\n");
      out.write("	padding: 50px;\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("	background-color: #f8f9fa; /* Change jumbotron background color */\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.1); /* Add shadow */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	max-width: 50%; /* Adjust content width */\r\n");
      out.write("	padding: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content h2 {\r\n");
      out.write("	font-size: 3rem;\r\n");
      out.write("	font-weight: 550;\r\n");
      out.write("	color: #007bff; /* Change heading color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content h4 {\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	margin-bottom: 15px; /* Add some space below subheading */\r\n");
      out.write("	font-style: oblique;\r\n");
      out.write("	font-family: cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content p {\r\n");
      out.write("	font-size: 1.2rem;\r\n");
      out.write("	line-height: 1.6; /* Increase line height for better readability */\r\n");
      out.write("	text-align: justify;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("	background-color: #2b92ff;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 20px 0;\r\n");
      out.write("	margin-top: auto; /* Push to bottom */\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column; /* Align images vertically */\r\n");
      out.write("	justify-content: center; /* Center images vertically */\r\n");
      out.write("	align-items: center; /* Center images horizontally */\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-container img {\r\n");
      out.write("	max-width: 90%; /* Reduce image width */\r\n");
      out.write("	height: auto;\r\n");
      out.write("	margin: 10px; /* Add margin between images */\r\n");
      out.write("	border-radius: 20px; /* Add border radius to images */\r\n");
      out.write("	box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1); /* Add shadow */\r\n");
      out.write("	animation: slideUp 1s ease;\r\n");
      out.write("	transition: transform 0.3s ease; /* Smooth transition on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-container img:hover {\r\n");
      out.write("	transform: scale(1.05); /* Scale image on hover */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("			<p class=\"navbar-brand\" style=\"font-family: cursive; margin-top:16px\">MediSlot</p>\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"navbar-collapse\">\r\n");
      out.write("					<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"jumbotron\">\r\n");
      out.write("		<div class=\"content text-center\" style=\"color: black\">\r\n");
      out.write("			<h2 class=\"display-4 mb-3\">About Us</h2>\r\n");
      out.write("			<h4>Welcome to MediSlot - Your trusted partner in healthcare</h4>\r\n");
      out.write("			<p>Welcome to MediSlot, where we're on a mission to transform the\r\n");
      out.write("				way you access healthcare. Founded with a vision of making quality\r\n");
      out.write("				healthcare more accessible and convenient for everyone, MediSlot is\r\n");
      out.write("				your go-to destination for seamless appointment booking and\r\n");
      out.write("				healthcare management. At MediSlot, we understand the frustration\r\n");
      out.write("				and challenges that often accompany the traditional healthcare\r\n");
      out.write("				system. Long wait times, confusing appointment processes, and\r\n");
      out.write("				limited access to healthcare providers can make managing your health\r\n");
      out.write("				a daunting task. That's why we've made it our goal to simplify and\r\n");
      out.write("				streamline the entire healthcare experience. Our platform is\r\n");
      out.write("				designed with you in mind, putting the power of healthcare\r\n");
      out.write("				management directly into your hands. Whether you're scheduling a\r\n");
      out.write("				routine check-up, seeking specialized care, or simply in need of\r\n");
      out.write("				urgent medical attention, MediSlot is here to help. With a\r\n");
      out.write("				comprehensive network of trusted healthcare providers and a\r\n");
      out.write("				user-friendly interface, finding and booking appointments has never\r\n");
      out.write("				been easier. But MediSlot is more than just a booking platform.\r\n");
      out.write("				We're committed to fostering a community of health-conscious\r\n");
      out.write("				individuals who prioritize their well-being.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"image-container\">\r\n");
      out.write("			<img src=\"assets/image/about_image.png\" alt=\"Appointment Booking\"\r\n");
      out.write("				class=\"img-fluid rounded\" /> <img\r\n");
      out.write("				src=\"assets/image/index_image1.png\" alt=\"Appointment Booking\"\r\n");
      out.write("				class=\"img-fluid rounded\" />\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<span>&copy; MediSlot. All rights reserved.</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
