/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-04-21 12:22:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.mediSlot.dao.*;
import com.mediSlot.model.*;
import com.mediSlot.util.*;
import com.mediSlot.service.*;

public final class patient_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("com.mediSlot.model");
    _jspx_imports_packages.add("com.mediSlot.service");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.mediSlot.dao");
    _jspx_imports_packages.add("com.mediSlot.util");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>MediSlot</title>\r\n");
      out.write("<link href=\"assets/image/icon.png\" rel=\"icon\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("/* Custom CSS styles */\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #2b92ff;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("	border-bottom: 2px solid #93c7ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #ffffff !important;\r\n");
      out.write("	justify-content: left;\r\n");
      out.write("	align-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	color: #ffffff !important;\r\n");
      out.write("	border: 1px solid rgb(242, 242, 242); /* Add border */\r\n");
      out.write("	border-radius: 0.6rem;\r\n");
      out.write("	padding: 0.2rem; /* Add padding */\r\n");
      out.write("	margin: 1rem;\r\n");
      out.write("	transition: transform 0.3s ease; /* Smooth transition on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("	border-color: rgba(56, 75, 179, 0.5); /* Change border color on hover */\r\n");
      out.write("	transform: translateY(-3px); /* Move link up slightly */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".feature {\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	flex-grow: 1; /* Fill remaining space */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center; /* Center horizontally */\r\n");
      out.write("	align-items: center; /* Center vertically */\r\n");
      out.write("	flex-direction: column; /* Stack items vertically */\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".feature h2 {\r\n");
      out.write("	color: #007bff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".feature p {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	border-color: #007bff;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("	background-color: #0056b3;\r\n");
      out.write("	border-color: #0056b3;\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("	background-color: #2b92ff;\r\n");
      out.write("	padding: 20px 0;\r\n");
      out.write("	margin-top: auto; /* Push to bottom */\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer span {\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	try {
		session = request.getSession(false);
		if (session != null) {
			String phoneNo = (String) session.getAttribute("phoneNo");
			DBConnection dbConnection = DBConnection.getDbConnection();
			PatientDao patientDao = new PatientDao(dbConnection);
			PatientService patientService = new PatientService(patientDao);
			Patient patient = patientService.findByPhoneNo(phoneNo);
	
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("			<p class=\"navbar-brand\"\r\n");
      out.write("				style=\"font-family: cursive; margin-top: 16px\">MediSlot</p>\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"navbar-collapse\">\r\n");
      out.write("					<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("						<li class=\"nav-item nav-link\"\r\n");
      out.write("							style=\"border: 0px; font-weight: bolder; font-size: 1.2rem;\">Welcome!\r\n");
      out.write("							");
      out.print(patient.getFullName());
      out.write("</li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"logout\">Logout</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"appointment\" class=\"feature\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\" style=\"text-align: center\">\r\n");
      out.write("					<h2>Book an Appointment</h2>\r\n");
      out.write("					<p>Ready to schedule your appointment? Click below to book now!</p>\r\n");
      out.write("					<a href=\"appointment.jsp\" class=\"btn btn-primary\">Book\r\n");
      out.write("						Appointment</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"upcoming-appointments\" class=\"feature\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\" style=\"text-align: center\">\r\n");
      out.write("					<h2>All Appointments</h2>\r\n");
      out.write("					<p>See your all appointment.</p>\r\n");
      out.write("					<a href=\"patients_appointment.jsp\" class=\"btn btn-primary\">See\r\n");
      out.write("						Appointment</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"medical-records\" class=\"feature\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\" style=\"text-align: center\">\r\n");
      out.write("					<h2>Medical Records</h2>\r\n");
      out.write("					<p>See your all medical records</p>\r\n");
      out.write("					<a href=\"medical_record.jsp\" class=\"btn btn-primary\">See\r\n");
      out.write("						Medical Record</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<span>&copy; 2024 MediSlot. All rights reserved.</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	} else {
	request.getRequestDispatcher("index.jsp").include(request, response);
	}
	}

	catch (Exception e) {

	response.sendRedirect("error.jsp");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
